### ISSUE TITLE
Confusion regarding the inference speed of Monst3r.

### ISSUE THREAD

**Issue by Yuhuoo** [Junyi42/monst3r#10]
Thanks for your nice work!
I have a confusion regarding inference speed. In your paper, you claim that the inference time of Monst3r on the A6000 is only 30s. I conducted a practical test with 50 images and found that the inference time for dust3r is about 30s, global alignment takes approximately 50s, and the final optimization requires nearly 2 minutes.

![image](https://github.com/user-attachments/assets/606774e9-db6c-4d36-a09b-74a4afd17c6c)

![image](https://github.com/user-attachments/assets/444755af-2334-4335-adf6-d717b39e4991)
![4098b6c6205ff35c2e9c741f7674075](https://github.com/user-attachments/assets/ec8c75f6-10cd-4eae-b655-f2cace36003c)

Am I mistaken in my understanding?

**Comment by Junyi42** [comment]
Hi @Yuhuoo,

Thanks for your interest in our work!

We mentioned in our paper that global optimization also takes one minute. Plus, the GPU we were using, RTX 6000 Ada, should be faster than RTX A6000, which may also be a reason.
<img width="726" alt="image" src="https://github.com/user-attachments/assets/bdd2463e-e968-4e77-8ed6-733609fc4d1b">

Feel free to let me know if you have any questions!

Thanks.
