### ISSUE TITLE
Error Evaluating on Sintel

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#11]
I was running the evaluation results on sintel but face the following error:

![image](https://github.com/user-attachments/assets/115894ce-7300-400a-a816-3d8aea30122d)

Turns out, I had to add "sintel" into one of the choices here which resolved it. https://github.com/Junyi42/monst3r/blob/6117b33f2666e757502192e6c3cb5587346cd241/dust3r/training.py#L118

**Comment by Junyi42** [comment]
Thanks! We will update the code.
