### ISSUE TITLE
Evaluation on the DAVIS dataset.

### ISSUE THREAD

**Issue by zhw-zhang** [Junyi42/monst3r#13]
![image](https://github.com/user-attachments/assets/a0ddf5b3-0606-4fb9-9f80-a84988ad211c)

Hi, thanks for your great work. I followed your instructions to evaluate on the DAVIS dataset, but the metrics I obtained all seem to be zero. Is this normal?

**Comment by Junyi42** [comment]
Hi @zhw-zhang,

Thanks for your interest in our work. This is expected since there is no ground truth camera pose for DAVIS dataset.

You could use the `viser` visualization script (here https://github.com/Junyi42/monst3r?tab=readme-ov-file#evaluation) to qualitatively evaluate the result.

Best.

**Comment by zhw-zhang** [comment]
thanks.
