### ISSUE TITLE
Input a video

### ISSUE THREAD

**Issue by zhw-zhang** [Junyi42/monst3r#15]
![image](https://github.com/user-attachments/assets/07e221d4-bee2-4584-82db-e3fbd6d897d1)

Hi, when I try to use a video as input, I encounter an error. I checked the code, and it seems that support for video input in the .mp4 format has not been updated yet.

**Comment by Junyi42** [comment]
Hi, thanks for the feedback!

Currently, the video input is only supported for GUI demo. I will fix this very soon.

Best.

**Comment by Junyi42** [comment]
Updated, thanks again for pointing out the issue!
