### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by kexul** [Junyi42/monst3r#18]
Hi, thanks for the great work! Is is possible to disable some function to run in a 4090 24G card? I only need to estimate camera movement in my use case.

**Comment by Junyi42** [comment]
Hi @kexul,

Thanks for your interest in our work!

Currently, you could try reducing the input image size to fit it in a smaller GPU (e.g., `python demo.py --image_size 224`), though our model is trained with images of only size 512, which may cause some performance degradation.

Best.

**Comment by kexul** [comment]
> Hi @kexul,
> 
> Thanks for your interest in our work!
> 
> Currently, you could try reducing the input image size to fit it in a smaller GPU (e.g., `python demo.py --image_size 224`), though our model is only trained with images of size 512, which may cause some performance degradation.
> 
> Best.

Thanks! I'll try it.

**Comment by kexul** [comment]
> Hi @kexul,
> 
> Thanks for your interest in our work!
> 
> Currently, you could try reducing the input image size to fit it in a smaller GPU (e.g., `python demo.py --image_size 224`), though our model is only trained with images of size 512, which may cause some performance degradation.
> 
> Best.

Thank you so much! image size 224 takes about 20G vram, which just fit for me.
