### ISSUE TITLE
Kitti Dataset

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#24]
There seems to be something wrong with the scripts to download and process the KITTI datasets. The paths after downloading does not seem to match the ones in prepare_kitti.py, so the dataset does not seem to be processed properly. This is what my data is like after running the download kitti script.

![image](https://github.com/user-attachments/assets/2ad32edc-5d77-466d-93d4-a3e5f9769fc7)

Could you help to resolve this? Thank you so much and thanks for releasing all of your work so quickly!

**Comment by Junyi42** [comment]
Hi @Davidyao99,

Thanks for the feedback!

I noticed that there's a link error for this line: https://github.com/Junyi42/monst3r/blob/main/data/download_kitti.sh#L5
Could you please try using `wget https://s3.eu-central-1.amazonaws.com/avg-kitti/data_depth_annotated.zip` instead? I will also try and update it.

Best.

**Comment by Davidyao99** [comment]
Thank you, I believe the updated link provides the right downloads for the depth maps. However, there is still a bit of issue with preprocessing the rgb images. The path stated [here](https://github.com/Junyi42/monst3r/blob/de9243f0e5e1f2cea55a74a37e8fc7a8b85fb14f/datasets_preprocess/prepare_kitti.py#L37) does not seem to align with the directory paths that you get after downloading kitti using the download script. It seems to work after I made the following changes to replace line 37:

```
mid = "_".join(depth_file.split("/")[4].split("_")[:3])
image_file = depth_file.replace('val',mid).replace('proj_depth/groundtruth/image_02', 'image_02/data')
```

**Comment by Junyi42** [comment]
Thanks!! I have updated the repo based on this.
