### ISSUE TITLE
TUMD preprocessing issues

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#27]
I am trying to reproduce your results on TUMD but I notice that your preprocessing of the TUMD dataset seems a little strange. I am following your preprocessing script [here](https://github.com/Junyi42/monst3r/blob/30d497f6f8635dd06bf9029646850ae765851ae5/datasets_preprocess/prepare_tum.py#L36). This script takes the corresponding depth, rgb, and groundtruth poses from the TUM dataset.

However, the rgb, depth, and pose of the TUMD dataset is not aligned. For eg. the first rgb image does not correspond to the reading of the first ground truth camera pose. Additionally, the frequency that the images / poses are collected is different. If you check the names of the rgb files (representing the time it is taken), they are different from the timestamps in groundtruth.txt. I believe to get the right timestamps, you have to query for the pose values at the closest timestamp for each rgb image. 

In the original TUMD dataset website, they provide scripts to perform this alignment [here](https://svncvpr.in.tum.de/cvpr-ros-pkg/trunk/rgbd_benchmark/rgbd_benchmark_tools/src/rgbd_benchmark_tools/). Aligning the depthmap is in associate.py and retrieving the corresponding pose from groundtruth.txt can be found in evaluate_rpe.py.

Thank you, and amazing work! Not sure if this preprocessing is performed for your evaluation in the table in your paper, perhaps you might get better results!

**Comment by Junyi42** [comment]
Hi @Davidyao99,

Thanks for this valuable feedback!! 

We will look into this issue and update the results in the next version.

Thanks!

**Comment by Junyi42** [comment]
The code for preparing the TUM-Dynamics dataset evaluation is updated (commit https://github.com/Junyi42/monst3r/commit/ce88f01f7f882b99ef40196a1da4ec092e6e3abb). The experiment results will also be updated in the next version of paper. Thanks!
