### ISSUE TITLE
GPU Memory OOM

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#28]
I am facing OOM issues when trying to run on TUMD / Scannet datasets which contains 90 images. I am using a A6000 which has a gpu memory of 49 GB. I see a comment in your code [here](https://github.com/Junyi42/monst3r/blob/5598ccd4a9d585c0bfb8f4da30fcbf646d31057b/dust3r/pose_eval.py#L118C7-L118C8) that seems to suggest that I should be able to run the evaluation script with my gpu?

![image](https://github.com/user-attachments/assets/ca723f00-7acf-4a74-aa10-c1a7bab734bc)

I checked that the empty_cache is indeed True. The OOM issue seems to come up at around iteration 30 out of 300 in the global alignment stage. Do you have any recommendations for resolving this? Thank you!!

**Comment by Junyi42** [comment]
Hi @Davidyao99,

Thanks for the feedback!

The TUMD / Scannet datasets come with an image ratio of 4:3, which consumes more memory than other datasets with a 16:9 ratio or even larger ratio.

We tested the results of these two datasets with an A100 80G GPU. You could try to decrease the number of sampled pairs (by setting the argument [`--scene_graph_type`](https://github.com/Junyi42/monst3r/blob/5598ccd4a9d585c0bfb8f4da30fcbf646d31057b/dust3r/training.py#L96) to `swinstride-4-noncyclic` or `swinstride-3-noncyclic`).

Best.

**Comment by Davidyao99** [comment]
I see I see, thank you so much for your prompt response and help!
