### ISSUE TITLE
Scannet Pose

### ISSUE THREAD

**Issue by Davidyao99** [Junyi42/monst3r#29]
I notice that some of the scannet sequence has infinity values in their pose. This seems to be mentioned [here](https://github.com/ScanNet/ScanNet/issues/9). An example of such a sequence is scene0711_00.

Running your evaluation scripts leads to exceptions during the evaluation of these sequences. I am wondering did you simply skip these sequences during your evaluation of scannet?

**Comment by Junyi42** [comment]
Yes, sequences `711, 737, 750, 761, 791, 796` of the total 100 sequences are excluded for evaluation.
