### ISSUE TITLE
How to get/set camera lens?

### ISSUE THREAD

**Issue by antimattergroup** [Junyi42/monst3r#32]
Hello, I am currently trying to get the camera lens data during inference, but I am unable to locate the relevant output. Could you please guide me on how to set up or get the camera lens data for inference?

**Comment by Junyi42** [comment]
Hi @antimattergroup,

The camera intrinsics will be stored in `{save_folder}/pred_intrinsics.txt`, and the focal will be stored in `{save_folder}/pred_focal.txt`.

For example, running the following command:
```bash
python demo.py --input demo_data/lady-running --output_dir demo_tmp --seq_name lady-running
will output the camera focals to `demo_tmp/lady-running/pred_focal.txt`.
```
Feel free to reach out if you have any further questions. Thanks again!

Best.

**Comment by sczhou21** [comment]
Excuse me, I wonder whether the predicted intrinsics correspond to the resized image or the original image?
