### ISSUE TITLE
About Waymo training

### ISSUE THREAD

**Issue by Barrybarry-Smith** [Junyi42/monst3r#36]
Hi, thank you for sharing this wonderful work!

I would like to know if you use the point cloud in Waymo for global alignment, cause I see the point cloud and depth map is loaded during data preprocessing, however, the global alignment seems to use a randomly initialized depthmap. Thank you!

**Comment by Junyi42** [comment]
Hi @Barrybarry-Smith,

Could you please elaborate a bit more on the question? We do not run global alignment during training. During training, we only sample pairs from waymo (and all the other datasets).

Thanks.

**Comment by Barrybarry-Smith** [comment]
Apologize for the misunderstanding, I wonder during the global alignment, does waymo use depth map or point cloud from dataset, or just start with a random initialized depth map? Does the depth map defined in waymo.py be used afterwards? 
<img width="685" alt="截屏2024-10-31 13 11 26" src="https://github.com/user-attachments/assets/3c9bf8a2-6769-45f2-9fb2-5d897ad1152c">

Thanks

**Comment by Junyi42** [comment]
Hi,

Sorry that I still don't understand. The `depthmap` is only used for training and not for the global alignment.

Thanks.

**Comment by Barrybarry-Smith** [comment]
Hi, I think I get the point. Thanks again for your response!
