### ISSUE TITLE
waymo's pairmaking strategy doesn't match the paper?

### ISSUE THREAD

**Issue by lacayqwq** [Junyi42/monst3r#37]
Hello, in waymo_mask_pairs.py
![image](https://github.com/user-attachments/assets/898f5f1c-f8ca-412d-8fa8-5c5511212b52)
Here is an average sample of various strides, which is not consistent with what the paper said

**Comment by Junyi42** [comment]
Hi,

Thanks for the catch!

The Waymo dataset has a frame rate of 10Hz, unlike all the other datasets, which have ~30 fps. Therefore, even without reweighting different strides, the average frame interval will be closer to that of other datasets. We have also tried using reweighting for the Waymo dataset, but it does not affect the performance much.

Best.
