### ISSUE TITLE
inference stopped

### ISSUE THREAD

**Issue by JV-X** [Junyi42/monst3r#38]
Hello, I followed the readme document to build the monst3r environment. After uploading a 5-second video file on the gradio page, I clicked the run button, and the console began to print processing information, showing "Inference with model on 950 image pairs". However, when the progress bar reached 91%, it stopped, and I found that my computer's disk usage soared from 2% to 100%, and the memory usage was also full. The computer I use is Core i9-14900KF, the graphics card is RTX4090, and the memory is 16G. Can you provide some help so that I can complete my work?

**Comment by Junyi42** [comment]
Hi,

You may need to use less frames for the input. Running on 950 image pairs usually requires a GPU with 80GB VRAM. 

Thanks.

**Comment by JV-X** [comment]
> Hi,
> 
> You may need to use less frames for the input. Running on 950 image pairs usually requires a GPU with 80GB VRAM.
> 
> Thanks.

thanks for your reply !  I‘ll have a try, one more question, how to reduce the number of frames? Is there any parameter to control it?
