### ISSUE TITLE
Problem downloading point odyssey dataset

### ISSUE THREAD

**Issue by sfchng** [Junyi42/monst3r#39]
Hey @Junyi42 

I have been trying to download point odyssey train dataset from the provided link for two days but it keeps failing due to high traffic. Is there an alternative for me to download this dataset?

Cheers.

**Comment by Junyi42** [comment]
Hi @sfchng,

Unfortunately, I am not able to distribute the datasets. You may also raise an issue in their repo: https://github.com/y-zheng18/point_odyssey. 

Thanks!

**Comment by sfchng** [comment]
Fair enough. Thanks for the suggestion! Cheers.
