### ISSUE TITLE
No response after clicking the run button

### ISSUE THREAD

**Issue by JV-X** [Junyi42/monst3r#4]
I built the environment according to the dust3r and monst3r documents, started the demo service, and then selected the image file. Everything was normal, but after I clicked the run button, the service console did not print any output, just like I didn't click it. I added some debugging statements in the code and found that after clicking The bound recon_fun function was not triggered.
 ```
run_btn.click(fn=recon_fun,
          inputs=[inputfiles, schedule, niter, min_conf_thr, as_pointcloud,
                      mask_sky, clean_depth, transparent_cams, cam_size,
                      scenegraph_type, winsize, refid],
         outputs=[scene, outmodel, outgallery])
```
 I tried upgrading/downgrading my gradio and gradio-client versions, but still couldn't trigger this function.

**Comment by JV-X** [comment]
Finally I found the solution, this is a problem with network settings

**Comment by Junyi42** [comment]
Hi @JV-X,

Sorry for the late reply. I'm glad to hear that your issue is resolved.

Best
