### ISSUE TITLE
No visual result present

### ISSUE THREAD

**Issue by JunyuanDeng** [Junyi42/monst3r#41]
Hello, thanks for sharing the impressive work.

I ran 10 frame of the video, and results are saved:
![image](https://github.com/user-attachments/assets/44186aa6-a58a-472f-99b7-5a0dcf569e2d)

But when I launch the viser/visualizer_monst3r.py:
![image](https://github.com/user-attachments/assets/7ad26053-90d2-44dd-a033-7527bb2e51c9)

It has some error:
```
(monst3r) [junyuan.deng@gpu-4090-dev013 monst3r]$ python viser/visualizer_monst3r.py --data demo_tmp/NULL/
(viser) No client build found. Building now...
 * Environment already exists: /home/users/junyuan.deng/Programmes/monst3r/viser/src/viser/client/.nodeenv
Traceback (most recent call last):
  File "/home/users/junyuan.deng/Programmes/monst3r/viser/visualizer_monst3r.py", line 364, in <module>
    tyro.cli(main(
             ^^^^^
  File "/home/users/junyuan.deng/Programmes/monst3r/viser/visualizer_monst3r.py", line 32, in main
    server = viser.ViserServer()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/users/junyuan.deng/Programmes/monst3r/viser/src/viser/_viser.py", line 476, in __init__
    _client_autobuild.ensure_client_is_built()
  File "/home/users/junyuan.deng/Programmes/monst3r/viser/src/viser/_client_autobuild.py", line 65, in ensure_client_is_built
    node_bin_dir = _install_sandboxed_node()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/junyuan.deng/Programmes/monst3r/viser/src/viser/_client_autobuild.py", line 116, in _install_sandboxed_node
    assert (node_bin_dir / "npx").exists()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I update viser to the latest version according to this [issue](https://github.com/nerfstudio-project/viser/issues/308).

But then

There are no results found:
![image](https://github.com/user-attachments/assets/ca0e74a4-aeb8-48a2-b113-add9e0e92527)
What should I do to adjust?

**Comment by ShenhanQian** [comment]
The rendering is still empty after I re-installed node.js as advised above. In the end, I found that this line is blocking the program from continuing:
https://github.com/Junyi42/viser/blob/b467e2b1771e7e8964c919bdbf8aa675a1263338/visualizer_monst3r.py#L33-L34

I can skip this line by setting `share` to False, and the program run properly.

**Comment by Junyi42** [comment]
> The rendering is still empty after I re-installed node.js as advised above. In the end, I found that the line below is blocking the program: https://github.com/Junyi42/viser/blob/b467e2b1771e7e8964c919bdbf8aa675a1263338/visualizer_monst3r.py#L33-L34
> 
> I can skip this line by setting `share` to False, and the program run properly.

Thanks for the feedback! It seems that there are some issues with `viser` requesting a shared URL.
