### ISSUE TITLE
Mismatch in Pose Estimation Evaluation Metrics on TUM Dataset

### ISSUE THREAD

**Issue by littlepure2333** [Junyi42/monst3r#42]
Hi, thank you for open-sourcing this excellent work! I've rerun all the evaluations, and most of the results align with those reported in the paper. However, I noticed that the pose estimation results on the TUM dataset are much worse than reported.

My results are as follows:
Average ATE: 0.10395, Average RPE trans: 0.02226, Average RPE rot: 1.03657

Could you please take a look at this? Perhaps some parameters need adjustment.

Thanks in advance!

**Comment by Junyi42** [comment]
Hi,

Thanks for the feedback. Could you please check that you are using the latest release? We have updated several issues regarding the evaluation of TUM-Dynamics dataset. You could refer to #27 for more information.

We have also evaluated on the updated benchmark of our methods (note that _all the baselines need to be re-evaluated_):
|              | **ATE ⬇️** | **RPE_trans ⬇️** | **RPE_rot ⬇️** |
|--------------|------------|------------------|----------------|
| dust3r       | 0.127      | 0.062           | 3.099         |
| monst3r      | 0.072      | 0.018           | 0.845         |

We will update the results of all the methods in our next version.

Thanks.

**Comment by littlepure2333** [comment]
Hi @Junyi42 , thanks for your prompt reply! I confirm that I am using the latest version (commit 86e5b03). I re-cloned, re-downloaded, re-processed, and re-ran the code on the TUM dataset today, but the results remain unchanged. I am attaching the full logs for your reference.

```
tum-rgbd_dataset_freiburg3_sitting_halfsphere | ATE: 0.01440, RPE trans: 0.00953, RPE rot: 0.41121
0.01440
0.00953
0.41121
tum-rgbd_dataset_freiburg3_sitting_rpy | ATE: 0.03570, RPE trans: 0.00825, RPE rot: 0.66501
0.03570
0.00825
0.66501
tum-rgbd_dataset_freiburg3_sitting_static | ATE: 0.02453, RPE trans: 0.01236, RPE rot: 0.39474
0.02453
0.01236
0.39474
tum-rgbd_dataset_freiburg3_sitting_xyz | ATE: 0.02952, RPE trans: 0.01072, RPE rot: 0.37652
0.02952
0.01072
0.37652
tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34218, RPE trans: 0.06736, RPE rot: 1.62139
0.34218
0.06736
1.62139
tum-rgbd_dataset_freiburg3_walking_rpy | ATE: 0.18413, RPE trans: 0.03464, RPE rot: 3.10400
0.18413
0.03464
3.10400
tum-rgbd_dataset_freiburg3_walking_static | ATE: 0.01633, RPE trans: 0.01290, RPE rot: 0.31381
0.01633
0.01290
0.31381
tum-rgbd_dataset_freiburg3_walking_xyz | ATE: 0.18478, RPE trans: 0.02234, RPE rot: 1.40586
0.18478
0.02234
1.40586
Average ATE: 0.10395, Average RPE trans: 0.02226, Average RPE rot: 1.03657
tum-rgbd_dataset_freiburg3_sitting_halfsphere | ATE: 0.01440, RPE trans: 0.00953, RPE rot: 0.41121
0.01440
0.00953
0.41121
tum-rgbd_dataset_freiburg3_sitting_rpy | ATE: 0.03570, RPE trans: 0.00825, RPE rot: 0.66501
0.03570
0.00825
0.66501
tum-rgbd_dataset_freiburg3_sitting_static | ATE: 0.02453, RPE trans: 0.01236, RPE rot: 0.39474
0.02453
0.01236
0.39474
tum-rgbd_dataset_freiburg3_sitting_xyz | ATE: 0.02952, RPE trans: 0.01072, RPE rot: 0.37652
0.02952
0.01072
0.37652
tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34218, RPE trans: 0.06736, RPE rot: 1.62139
0.34218
0.06736
1.62139
tum-rgbd_dataset_freiburg3_walking_rpy | ATE: 0.18413, RPE trans: 0.03464, RPE rot: 3.10400
0.18413
0.03464
3.10400
tum-rgbd_dataset_freiburg3_walking_static | ATE: 0.01633, RPE trans: 0.01290, RPE rot: 0.31381
0.01633
0.01290
0.31381
tum-rgbd_dataset_freiburg3_walking_xyz | ATE: 0.18478, RPE trans: 0.02234, RPE rot: 1.40586
0.18478
0.02234
1.40586
tum-rgbd_dataset_freiburg3_sitting_halfsphere | ATE: 0.01440, RPE trans: 0.00953, RPE rot: 0.41121
0.01440
0.00953
0.41121
tum-rgbd_dataset_freiburg3_sitting_rpy | ATE: 0.03570, RPE trans: 0.00825, RPE rot: 0.66501
0.03570
0.00825
0.66501
tum-rgbd_dataset_freiburg3_sitting_static | ATE: 0.02453, RPE trans: 0.01236, RPE rot: 0.39474
0.02453
0.01236
0.39474
tum-rgbd_dataset_freiburg3_sitting_xyz | ATE: 0.02952, RPE trans: 0.01072, RPE rot: 0.37652
0.02952
0.01072
0.37652
tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34218, RPE trans: 0.06736, RPE rot: 1.62139
0.34218
0.06736
1.62139
tum-rgbd_dataset_freiburg3_walking_rpy | ATE: 0.18413, RPE trans: 0.03464, RPE rot: 3.10400
0.18413
0.03464
3.10400
tum-rgbd_dataset_freiburg3_walking_static | ATE: 0.01633, RPE trans: 0.01290, RPE rot: 0.31381
0.01633
0.01290
0.31381
tum-rgbd_dataset_freiburg3_walking_xyz | ATE: 0.18478, RPE trans: 0.02234, RPE rot: 1.40586
0.18478
0.02234
1.40586
Average ATE: 0.10395, Average RPE trans: 0.02226, Average RPE rot: 1.03657
```

**Comment by Junyi42** [comment]
> Hi @Junyi42 , thanks for your prompt reply! I confirm that I am using the latest version (commit [86e5b03](https://github.com/Junyi42/monst3r/commit/86e5b035c032b379ed4858d831e2ca25ac637565)). I re-cloned, re-downloaded, re-processed, and re-ran the code on the TUM dataset today, but the results remain unchanged. I am attaching the full logs for your reference.
> 
> ```
> tum-rgbd_dataset_freiburg3_sitting_halfsphere | ATE: 0.01440, RPE trans: 0.00953, RPE rot: 0.41121
> 0.01440
> 0.00953
> 0.41121
> tum-rgbd_dataset_freiburg3_sitting_rpy | ATE: 0.03570, RPE trans: 0.00825, RPE rot: 0.66501
> 0.03570
> 0.00825
> 0.66501
> tum-rgbd_dataset_freiburg3_sitting_static | ATE: 0.02453, RPE trans: 0.01236, RPE rot: 0.39474
> 0.02453
> 0.01236
> 0.39474
> tum-rgbd_dataset_freiburg3_sitting_xyz | ATE: 0.02952, RPE trans: 0.01072, RPE rot: 0.37652
> 0.02952
> 0.01072
> 0.37652
> tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34218, RPE trans: 0.06736, RPE rot: 1.62139
> 0.34218
> 0.06736
> 1.62139
> tum-rgbd_dataset_freiburg3_walking_rpy | ATE: 0.18413, RPE trans: 0.03464, RPE rot: 3.10400
> 0.18413
> 0.03464
> 3.10400
> tum-rgbd_dataset_freiburg3_walking_static | ATE: 0.01633, RPE trans: 0.01290, RPE rot: 0.31381
> 0.01633
> 0.01290
> 0.31381
> tum-rgbd_dataset_freiburg3_walking_xyz | ATE: 0.18478, RPE trans: 0.02234, RPE rot: 1.40586
> 0.18478
> 0.02234
> 1.40586
> Average ATE: 0.10395, Average RPE trans: 0.02226, Average RPE rot: 1.03657
> ```

Hi @littlepure2333, thanks for the feedback. The results on the `walking_halfsphere` looks weird to me. I also redownloaded  the repo and had a test on this sequence. Here's the trajectory I got (with the ATE around 0.10):

<img width="577" alt="image" src="https://github.com/user-attachments/assets/709325b3-2a52-4d2c-be91-888f9c26f092">

I will test on other sequences and update the results soon.

Best.

**Comment by kai422** [comment]
Is this because of different environment version? I also get similar results:
tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34412, RPE trans: 0.06800, RPE rot: 1.63494

**Comment by Junyi42** [comment]
> Is this because of different environment version? I also get similar results:
> tum-rgbd_dataset_freiburg3_walking_halfsphere | ATE: 0.34412, RPE trans: 0.06800, RPE rot: 1.63494

Hi,

Thanks for the feedback!

Could you please share the plotted trajectory? I'm caught up with a few things these two weeks, but I will look into this issue as soon as possible.

Thanks!

**Comment by kai422** [comment]
Sure. I also noticed you changed the motion mask threshold for sintel in one of the issues. Is the threshold the same for Tum dataset?

**Comment by kai422** [comment]
![Uploading image.png…]()

**Comment by lxin98** [comment]
May I ask how it runs on Tum? I disabled flow loss, but there is still a problem of insufficient GPU memory. My memory size is 24 @kai422 @littlepure2333

**Comment by littlepure2333** [comment]
@lxin98 Hi I run it on H100 for high GPU memory occupation.
