### ISSUE TITLE
Can I export point clouds and camera values? 

### ISSUE THREAD

**Issue by thewaylord** [Junyi42/monst3r#5]
Can I export point clouds and camera values? 
Will I be able to use this data in other 3D tools?

**Comment by antithing** [comment]
+1

**Comment by Junyi42** [comment]
Hi @antithing and @thewaylord,

Yes, we will export point clouds and camera values (extrinsic and intrinsic). The camera format will be `t x y z qw qx qy qz`. Please stay tuned for the release. Thanks for your patience.

Best.

**Comment by Junyi42** [comment]
Hi,

Thank you for your patience! We have now released the code for inference. The point cloud will be saved as `{save_folder}/scene.glb`, camera poses will be stored in `{save_folder}/pred_traj.txt`, and camera intrinsics in `{save_folder}/pred_intrinsics.txt`.

For example, running the following command:

```bash
python demo.py --input demo_data/lady-running --output_dir demo_tmp --seq_name lady-running
```
will output the camera trajectory to `demo_tmp/lady-running/pred_traj.txt`.

Feel free to reach out if you have any further questions. Thanks again!

Best.
