### ISSUE TITLE
How to deal with vertical images

### ISSUE THREAD

**Issue by ZeroWen** [Junyi42/monst3r#52]
Dear Authors,
Thank you for sharing this amazing work!
I see that the code clearly states that the video length needs to be greater than the height
![image](https://github.com/user-attachments/assets/ac74aee2-671a-4806-9132-bdc15e40e9d2)
When I pass in a video that is taller than wide, the code gets an error
How to correctly handle videos that are higher than they are wide

**Comment by Junyi42** [comment]
Hi, could you please elaborate more on how you encountered the error?

A temporal solution is to download the checkpoint `gdown --fuzzy https://drive.google.com/file/d/1Z1jO_JmfZj0z3bgMvCwqfUhyZ1bIbc9E/view?usp=sharing` in `checkpoints` folder, and run `python demo.py`. Then, the patch embedding will be set to be `PatchEmbedDust3R` hence skip the assertion in `ManyAR_PatchEmbed`.

Best.

**Comment by ZeroWen** [comment]
> Hi, could you please elaborate more on how you encountered the error?
> 
> A temporal solution is to download the checkpoint `gdown --fuzzy https://drive.google.com/file/d/1Z1jO_JmfZj0z3bgMvCwqfUhyZ1bIbc9E/view?usp=sharing` in `checkpoints` folder, and run `python demo.py`. Then, the patch embedding will be set to be `PatchEmbedDust3R` hence skip the assertion in `ManyAR_PatchEmbed`.
> 
> Best.

**Comment by ZeroWen** [comment]
> Hi, could you please elaborate more on how you encountered the error?
> 
> A temporal solution is to download the checkpoint `gdown --fuzzy https://drive.google.com/file/d/1Z1jO_JmfZj0z3bgMvCwqfUhyZ1bIbc9E/view?usp=sharing` in `checkpoints` folder, and run `python demo.py`. Then, the patch embedding will be set to be `PatchEmbedDust3R` hence skip the assertion in `ManyAR_PatchEmbed`.
> 
> Best.

Thank you very much;
I realized that I didn't succeed in downloading the pre-trained model；When the pretrained model was downloaded, the problem was resolved
